# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-24 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='granted_wish',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='wishing_app.User'),
        ),
    ]
